

services:
  database:
    image: postgres:15
    container_name: postgres_prisma_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: futarian@20
      POSTGRES_DB: prisma-with-postgresql
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: express_prisma_api
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:futarian%4020@postgres_prisma_db:5432/prisma-with-postgresql?schema=public
    ports:
      - '3003:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ['sh', '-c', 'npx prisma generate && node src/server.js']

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_prisma
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9091:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: prisma_grafana
    restart: always
    ports:
      - '3005:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:
